### ISSUE TITLE
한국어 문서

### ISSUE THREAD

**Issue by meloalright** [meloalright/guora#27]
![ui](https://user-images.githubusercontent.com/11075892/90159118-80a65600-ddc2-11ea-91f4-b1afa0fe7818.png)

# Guora

[![go-report](https://goreportcard.com/badge/github.com/meloalright/guora)](https://goreportcard.com/report/github.com/meloalright/guora)[![codecov](https://codecov.io/gh/meloalright/guora/branch/master/graph/badge.svg)](https://codecov.io/gh/meloalright/guora)[![go-mod](https://img.shields.io/github/go-mod/go-version/meloalright/guora)](https://github.com/meloalright/guora)[![license](https://img.shields.io/github/license/meloalright/guora)](https://opensource.org/licenses/MIT)

🖖🏻  Go 로 작성된 자체 호스팅 Quora 와 같은 웹 애플리케이션

## 빠른 시작 (Docker Deploy)

```sh
$ docker-compose up --build
```

### 1.클론 소스 코드

```shell
$ git clone https://github.com/meloalright/guora

$ cd guora
```

### 2.다운로드 의존하다

```shell
$ go mod download
```

### 3.창조하다 구성

```shell
$ touch /etc/guora/configuration.yaml
```

```yaml
# 디버깅 구성
db:
  driver: sqlite3
  addr: ./guora.db
  # driver: mysql
  # addr: user:password@/dbname?charset=utf8&parseTime=True&loc=Local
  # driver: postgres
  # addr: host=myhost user=gorm dbname=gorm sslmode=disable password=mypassword
redis:
  addr: localhost:6379
  password:
  db: 0
admin:
  name: Development (개발계정)
  mail: mymail
  password: mypassword
secretkey: 당신이 좋아하는 무엇이든 쓰십시오
lang: en
#lang: zh
address: :8080
```

| 매개변수     | 설명                                           |
| --------- | ----------------------------------------------------- |
| db        | 데이터베이스 구성 sqlite3, mysql, postgres 지원 |
| redis     | Redis 구성                                       |
| admin     | 관리자 정보                                  |
| secretkey | 토큰 서명을 위한 비밀 문자열                    |
| lang      | 언어 한국어 버전은 아직 지원되지 않습니다                    |
| address   | 감시 장치 주소                                     |

### 4.초기화 및 시작

```shell
$ (sudo) go run ./cmd/guora -init
```

### 5. 웹사이트 방문

방문 [localhost:8080](http://localhost:8080) 그리고 관리자로 로그인

|                     |            |
| ------------------- | ---------- |
| mail (기본 사서함)     | mymail     |
| password (기본 사서함) | mypassword |

## 테스트

```shell
$ (sudo) go test ./cmd/guora
```

## 소스 코드

창고: [guora](https://github.com/meloalright/guora)

작가: [meloalright](https://github.com/meloalright)

기부자: [contributors](https://github.com/meloalright/guora/graphs/contributors)

## 업데이트 로그

Documented in [Releases](https://github.com/meloalright/guora/releases)

## 라이센스

[MIT](https://opensource.org/licenses/MIT)
